//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularPostGet.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablo1
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
    }
}
